require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/workout_sets", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WorkoutSet. As you add validations to WorkoutSet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WorkoutSet.create! valid_attributes
      get workout_sets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      workout_set = WorkoutSet.create! valid_attributes
      get workout_set_url(workout_set)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_workout_set_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      workout_set = WorkoutSet.create! valid_attributes
      get edit_workout_set_url(workout_set)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WorkoutSet" do
        expect {
          post workout_sets_url, params: { workout_set: valid_attributes }
        }.to change(WorkoutSet, :count).by(1)
      end

      it "redirects to the created workout_set" do
        post workout_sets_url, params: { workout_set: valid_attributes }
        expect(response).to redirect_to(workout_set_url(WorkoutSet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WorkoutSet" do
        expect {
          post workout_sets_url, params: { workout_set: invalid_attributes }
        }.to change(WorkoutSet, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post workout_sets_url, params: { workout_set: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested workout_set" do
        workout_set = WorkoutSet.create! valid_attributes
        patch workout_set_url(workout_set), params: { workout_set: new_attributes }
        workout_set.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the workout_set" do
        workout_set = WorkoutSet.create! valid_attributes
        patch workout_set_url(workout_set), params: { workout_set: new_attributes }
        workout_set.reload
        expect(response).to redirect_to(workout_set_url(workout_set))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        workout_set = WorkoutSet.create! valid_attributes
        patch workout_set_url(workout_set), params: { workout_set: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested workout_set" do
      workout_set = WorkoutSet.create! valid_attributes
      expect {
        delete workout_set_url(workout_set)
      }.to change(WorkoutSet, :count).by(-1)
    end

    it "redirects to the workout_sets list" do
      workout_set = WorkoutSet.create! valid_attributes
      delete workout_set_url(workout_set)
      expect(response).to redirect_to(workout_sets_url)
    end
  end
end
